language: node_js
node_js:
  - "10"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - chown -R $USER:$USER /home/travis/virtualenv/python2.7.12/bin/
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser
script:
  - npm run test